# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Haha' do
  before(:each) do
    @driver = Selenium::WebDriver.for :chrome
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'haha' do
    @driver.get('http://practice.automationtesting.in/')
    @driver.manage.resize_to(1382, 784)
    @driver.find_element(:link_text, 'My Account').click
    @driver.find_element(:id, 'reg_email').click
    @driver.find_element(:id, 'reg_email').send_keys('tai1212@gmail.com')
    @driver.find_element(:id, 'reg_password').send_keys('tai0889454689')
    @driver.find_element(:name, 'register').click
  end
end
